### Задание 1

In [40]:
import numpy as np
start_digit = int(input('Введите начало отсчета массива: ')) - 1
np.arange(start_digit, -1, -1)

Введите начало отсчета массива: 15


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

In [42]:
import numpy as np
start_digit = int(input('Введите начало отсчета массива: ')) - 1
diag_array = np.array(np.diag(np.arange(start_digit, -1, -1)))
sum_diag_array = np.sum(diag_array)
print(diag_array)
print('Сумма элементов массива:', sum_diag_array)

Введите начало отсчета массива: 15
[[14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
Сумма элементов массива: 105


### Задание 3

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [43]:
import numpy as np
from numpy import linalg

a = np.array( [ [4, 2, 1],
                [1, 3, 0],
                [0, 5, 4]
              ] )
b = np.array( [4, 12, -3] )

print('Решение системы уравнений:', linalg.solve(a,b))

Решение системы уравнений: [ 0.46666667  3.84444444 -5.55555556]


### Задание 4

In [45]:
import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats_length = linalg.norm(next_user_stats)

users_correlation_dict = {}

for i, user in enumerate(users_stats):
    key_name = 'user' + str(i + 1)
    dot_product = np.dot(user, next_user_stats)
    cos_similarity = round(dot_product / (linalg.norm(user) * next_user_stats_length), 5)
    users_correlation_dict[key_name] = cos_similarity
{x: y for x, y in filter(lambda x: users_correlation_dict[x[0]] == max(users_correlation_dict.values()), users_correlation_dict.items())}

{'user8': 0.94868}